config/routes.rb
Rails.application.routes.draw do
  resources :users
  resources :homes

  root 'homes#homeview'
  get 'signup', to: "users#new"

 
  
  resources :articles

 get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'

   resources :categories, except: [:destroy]

end

app/models/article.rb
class Article < ActiveRecord::Base
	belongs_to:user
	validates :title, presence:true, length: {minimum:10, maximum:50}
	validates :user_id, presence:true
end

app/models/category.rb
class Category < ActiveRecord::Base
	validates :name, presence: true, length: { minimum: 3, maximum: 25 }
	validates_uniqueness_of :name
end

app/models/home.rb
class Home < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
	has_many:articles, dependent: :destroy
	before_save { self.email = email.downcase }

	
	VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
	validates :email, presence: true, length: { maximum: 105 },
	uniqueness: { case_sensitive: false },
	format: { with: VALID_EMAIL_REGEX }
	has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  helper_method :current_user, :logged_in?
  	def current_user
		@current_user ||= User.find(session[:user_id]) if session[:user_id]
	end
	def logged_in?
		!!current_user
	end
	def require_user
		if !logged_in?
		flash[:danger] = "You must be logged in to perform that action"
		redirect_to root_path
		end
	end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController

	before_action :set_article, only: [:edit, :update, :show, :destroy]
	before_action :require_user, except: [:index, :show]
	before_action :require_same_user, only: [:edit, :update, :destroy]
	def index
		#@articles=Article.all
		@articles = Article.paginate(page: params[:page], per_page: 5)
	end
	def new
		@article = Article.new
	end
	def create
		#render plain: params[:article].inspect
		@article=Article.new(article_params)
		@article.user = current_user
		if @article.save
			flash[:notice]="article created successfully"
		redirect_to article_path(@article)
		else
			render 'new'
		end
	end
	def show
		@article=Article.find(params[:id])
		
	end
	def edit
		@article=Article.find(params[:id])
	end
	def update
		@article=Article.find(params[:id])
		if@article.update(article_params)
			flash[:notice]="artical updated suceesfully"
			redirect_to article_path(@article)
		else
			render 'edit'
		end
	end
	def destroy
		@article = Article.find(params[:id])
		@article.destroy
		flash[:notice] = "Article was successfully deleted"
		redirect_to articles_path
	end
	def set_article
		@article = Article.find(params[:id])
	end
	def require_same_user
		if current_user != @article.user and !current_user.admin?
		flash[:danger] = "You can only edit or delete your own articles"
		redirect_to root_path
		end
	end
	private
		def article_params
			params.require(:article).permit(:title , :description)
		end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
	def index
		@categories = Category.paginate(page: params[:page], per_page: 5)
	end
	def new
		@category = Category.new
	end
	def create
		@category = Category.new(category_params)
		if @category.save
			flash[:success] = "Category was created successfully"
			redirect_to categories_path
		else
			render 'new'
		end
	end

	def show
	end

	private
	def category_params
		params.require(:category).permit(:name)
	end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  before_action :set_home, only: [:show, :edit, :update, :destroy]

  # GET /homes
  # GET /homes.json
  def index
    @homes = Home.all
  end

  # GET /homes/1
  # GET /homes/1.json
  def show
  end

  # GET /homes/new
  def new
    @home = Home.new
  end

  # GET /homes/1/edit
  def edit
  end

  # POST /homes
  # POST /homes.json
  def create
    @home = Home.new(home_params)

    respond_to do |format|
      if @home.save
        format.html { redirect_to @home, notice: 'Home was successfully created.' }
        format.json { render :show, status: :created, location: @home }
      else
        format.html { render :new }
        format.json { render json: @home.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /homes/1
  # PATCH/PUT /homes/1.json
  def update
    respond_to do |format|
      if @home.update(home_params)
        format.html { redirect_to @home, notice: 'Home was successfully updated.' }
        format.json { render :show, status: :ok, location: @home }
      else
        format.html { render :edit }
        format.json { render json: @home.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /homes/1
  # DELETE /homes/1.json
  def destroy
    @home.destroy
    respond_to do |format|
      format.html { redirect_to homes_url, notice: 'Home was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_home
      @home = Home.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def home_params
      params.require(:home).permit(:name, :add)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
	
	def new
	end

	def create
		user = User.find_by(email: params[:session][:email].downcase)
		if user && user.authenticate(params[:session][:password])
			session[:user_id] = user.id
			flash[:success] = "You have successfully logged in"
			redirect_to user_path(user)
		else
			flash.now[:danger] = "There was something wrong with your login information"
			render 'new'
		end
	end

	def destroy
		session[:user_id] = nil
		flash[:success] = "You have logged out"
		redirect_to root_path
	end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	
	before_action :set_user, only: [:edit, :update, :show]	
	before_action :require_same_user, only: [:edit, :update, :destroy]
	before_action :require_admin, only: [:destroy]
		def index
			#@users=User.all
			@users = User.paginate(page: params[:page], per_page: 5)
		end		

		def new
			@user=User.new
		end
		def create
			@user = User.new(user_params)
			if @user.save
			session[:user_id] = @user.id
			flash[:success] = "Welcome to the alpha blog #{@user.username}"
			redirect_to user_path(@user)
			else
			render 'new'
			end
		end
		def edit
			#@user = User.find(params[:id])
			#@user.email = params[:email]
		end
		def update
			#@user = User.find(params[:id])
			if@user.update(user_params)
			flash[:notice]="user updated suceesfully"
			redirect_to articles_path
			#redirect_to article_path(@user)
			else
				render 'edit'
			end
			#@user.email = params[:email]
		end
		def destroy
			@user = User.find(params[:id])
			@user.destroy
			flash[:notice] = "user and articles created by user has been deletedd"
			redirect_to users_path
		end
		def show
			#@user = User.find(params[:id])
			@user_articles = @user.articles.paginate(page: params[:page], per_page: 5)
			#redirect_to users_path(@users)

		end
		def set_user
			@user = User.find(params[:id])
		end
		private
			def user_params			
			params.require(:user).permit(:username,:email, :password)
		end
		def require_same_user
			if current_user != @user and !current_user.admin?
			flash[:danger] = "You can only edit or delete your own articles"
			redirect_to root_path
			end
		end
		def require_admin
			if logged_in? and !current_user.admin?
			flash[:danger] = "Only admin users can perform that action"
			redirect_to root_path
			end
		end
end

app/helpers/application_helper.rb
module ApplicationHelper

	def gravatar_for(user, options = { size: 80})
		gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
		size = options[:size]
		gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
		image_tag(gravatar_url, alt: user.username, class: "img-circle")
	end
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/articles/_article.html.erb
<% obj.each do |article| %>
<div class="row">
<div class="col-xs-8 col-xs-offset-2">
<div class="well well-lg">
<div class="article-title">
<%= link_to article.title, article_path(article) %>
</div>
<div class="article-body">
<%= truncate(article.description, length: 100) %>
<div class="article-meta-details">
<small>Created by: <%= article.user.username if article.user%>,
<%= time_ago_in_words(article.created_at) %> ago,
last updated: <%= time_ago_in_words(article.updated_at) %> ago</small>
</div>
</div>
<% if logged_in? && (current_user == article.user || current_user.admin?) %>
<div class="article-actions">
<%= link_to "Edit this article", edit_article_path(article), class: "btn btn-xs btn-primary" %>
<%= link_to "Delete this article", article_path(article), method: :delete,
data: { confirm: "Are you sure you want to delete the article?"},
class: "btn btn-xs btn-danger" %>
</div>
<% end %>
</div>
</div>
</div>
<% end %>

app/views/articles/_form.html.erb
<% if @article.errors.any? %>
	<ul>
	<% @article.errors.full_messages.each do|msg| %>
		<li><%=  msg %></li>
	<% end %>

	</ul>
<% end %>

<%= form_for @article do |f| %>
	<p>
		<%= f.label :title %><br/>
		<%= f.text_field :title %>
	</p>
	<p>
		<%= f.label :description %><br/>
		<%= f.text_area :description %>
	</p>
	<p>
		<%= f.submit %>
	</p>
<% end %>

app/views/articles/edit.html.erb
<h1>Articles Page</h1>
<%= render "form" %> 

app/views/articles/index.html.erb
<h1><center> Articles list</center></h1>
<%= link_to "Add+" ,new_article_path, class: "btn btn-primary btn-md", role: "button", id: "btn_add" %><br>
<br>

-------------view--------------
<%= render 'article', obj: @articles %>
<div align="center">
<%= will_paginate %>
</div>
-----------view----------------------



 <table class="table table-striped">
    <thead>
      <tr>
      <tr>
		<th>Article </th>
		<th>Description </th>
        <th >Edit</th>
        <th>Show</th>
        <th>Delete</th>
      </tr>
    </thead>
    <tbody>
     <% @articles.each do |article| %>
	<tr>
		<td> <%= article.title%></td>
		<td><%= article.description %><small> Created by <%= article.user.username if article.user%>
		Updated at <%= time_ago_in_words(article.updated_at)  %> ago</td>
<% if logged_in? && current_user == article.user %>
		<td>		
		<%= link_to edit_article_path(article) do %>
  		<i class="fa fa-pencil-square-o fa-lg"></i> 
		<% end %>
		</td>
		<td>		
		<%= link_to article_path(article) do %>
  		<i class="fa fa-eye fa-lg"></i> 
		<% end %>
		</td>
		
		<td>		
		<%= link_to article_path(article) , method: :delete, data: {confirm: "Are you sure?"}  do %>
  		<i class="fa fa-trash-o fa-lg"></i> 
		<% end %>
		</td>
	<% end %>
	</tr>
<% end %>
    </tbody>
  </table>

app/views/articles/new.html.erb
<h1>Articles Page</h1>
<%= form_for @article do |f| %>
<p>
<%= f.label :title %><br/>
<%= f.text_field :title %>
</p>
<p>
<%= f.label :description %><br/>
<%= f.text_area :description %>
</p>
<p>
<%= f.submit %>
</p>
<% end %>

app/views/articles/show.html.erb
<p>Title <%= @article.title %></p>

<p>Description <%= @article.description %> </>

<h1 align="center">Title: <%= @article.title %></h2>
<div class="row" align="center">
<div class="well col-xs-8 col-xs-offset-2">
<% if @article.user %>
<ul class="listing">
<div class="row center">
<div class="col-md-4 col-md-offset-4">
<li>Created by:</li>
<li><%= link_to gravatar_for(@article.user), user_path(@article.user) %></li>
<li class="article-title">
<%= link_to @article.user.username, user_path(@article.user) %>
</li>
<li><small>
<%= pluralize(@article.user.articles.count, "article") if @article.user.articles %>
</small></li>
</div>
</div>
</ul>
<% end %>
<h4 class="center description"><strong>Description:</strong></h4>
<hr>
<%= simple_format(@article.description) %>
<% if logged_in? && (current_user == @article.user || current_user.admin?) %>
<div class="article-actions">
<%= link_to "Edit this article", edit_article_path(@article), class: "btn btn-xs btn-primary" %>
<%= link_to "Delete this article", article_path(@article), method: :delete,
data: { confirm: "Are you sure you want to delete the article?"},
class: "btn btn-xs btn-danger" %>
<% end %>
<%= link_to "View all articles", articles_path, class: "btn btn-xs btn-success" %>
</div>
</div>
</div>

app/views/categories/index.html.erb
<h1 align="center">Listing All Categories</h1>
<div align="center">
<%= will_paginate %>
	<% @categories.each do |category| %>
	<ul class="listing">
		<div class="row">
			<div class="well col-md-4 col-md-offset-4">
				<li class="article-title">
				<%= link_to "#{category.name}", category_path(category) %>
				</li>
			</div>
		</div>
	</ul>
	<% end %>
</div>

app/views/categories/new.html.erb
<h1 align="center">Create new category</h1>


<%= form_for(@category, :html => {class: "form-horizontal", role: "form"}) do |f| %>
<div class="form-group">
	<div class="control-label col-sm-2">
	<%= f.label :name %>
	</div>
	<div class="col-sm-8">
	<%= f.text_field :name, class: "form-control", placeholder: "Category name", autofocus: true %>
	</div>
</div>
<div class="form-group">
	<div class="col-sm-offset-2 col-sm-10">
	<%= f.submit class: 'btn btn-primary btn-lg' %>
	</div>
</div>
<% end %>
<div class="col-xs-4 col-xs-offset-4">
[ <%= link_to "Cancel request and return to articles listing", articles_path %> ]
</div>

app/views/homes/_form.html.erb
<%= form_for(@home) do |f| %>
  <% if @home.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@home.errors.count, "error") %> prohibited this home from being saved:</h2>

      <ul>
      <% @home.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :add %><br>
    <%= f.text_field :add %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/homes/edit.html.erb
<h1>Editing Home</h1>

<%= render 'form' %>

<%= link_to 'Show', @home %> |
<%= link_to 'Back', homes_path %>

app/views/homes/homeview.html.erb
<div class="jumbotron" style="text-align:center">
  <h1>Welcome</h1>
  
  <p>
 <%= link_to "Sign Up", "#", class: "tn btn-primary btn-lg", role:"button", id:"btn_signup" %>
  </p>
</div>

app/views/homes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Homes</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Add</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @homes.each do |home| %>
      <tr>
        <td><%= home.name %></td>
        <td><%= home.add %></td>
        <td><%= link_to 'Show', home %></td>
        <td><%= link_to 'Edit', edit_home_path(home) %></td>
        <td><%= link_to 'Destroy', home, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Home', new_home_path %>

app/views/homes/new.html.erb
<h1>New Home</h1>

<%= render 'form' %>

<%= link_to 'Back', homes_path %>

app/views/homes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @home.name %>
</p>

<p>
  <strong>Add:</strong>
  <%= @home.add %>
</p>

<%= link_to 'Edit', edit_home_path(@home) %> |
<%= link_to 'Back', homes_path %>

app/views/layouts/_footer.html.erb
<footer>
<center>
  <p>Posted by: sonu pajai</p>
  <p>Contact information: <a href="mailto:someone@example.com">someone@example.com</a>.</p>
 </center>
</footer>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-default">
<div class="container-fluid">
<!-- Brand and toggle get grouped for better mobile display -->
<div class="navbar-header">
<button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
<span class="sr-only">Toggle navigation</span>
<span class="icon-bar"></span>
<span class="icon-bar"></span>
<span class="icon-bar"></span>
</button>
<%= link_to "Alpha blog", root_path, class: "navbar-brand intro", id: "logo" %>
</div>
<!-- Collect the nav links, forms, and other content for toggling -->
<div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
<ul class="nav navbar-nav">
<li><%= link_to "Articles", articles_path , class: "intro"%></li>
<li><%= link_to "Users", users_path , class: "intro"%></li>
<% if logged_in? %>
<li class="dropdown">
<a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Actions <span class="caret"></span></a>
<ul class="dropdown-menu">
<li><%= link_to "New Article", new_article_path  , class: "intro"%></li>
<li><a href="#">Another action</a></li>
<li><a href="#">Something else here</a></li>
<li role="separator" class="divider"></li>
<li><a href="#">Separated link</a></li>
<li role="separator" class="divider"></li>
<li><a href="#">One more separated link</a></li>
</ul>
</li>
<% end %>
</ul>
<form class="navbar-form navbar-left" role="search">
<div class="form-group">
<input type="text" class="form-control" placeholder="Search">
</div>
<button type="submit" class="btn btn-default">Submit</button>
</form>
<ul class="nav navbar-nav navbar-right">
<% if logged_in? %>
<li><%= link_to 'Log out', logout_path, method: :delete , class: "intro" %></li>
<li class="dropdown">
<a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Your Profile <%= "Admin" if current_user.admin? %><span class="caret"></span></a>
<ul class="dropdown-menu">
<li><%= link_to "Edit your profile", edit_user_path(current_user) %></li>
<li><%= link_to "View your profile", user_path(current_user) %></li>
<li><a href="#">Something else here</a></li>
<li role="separator" class="divider"></li>
<li><a href="#">Separated link</a></li>
</ul>
</li>
<% else %>
<li><%= link_to 'Log in', login_path  , class: "intro"%></li>
<li><%= link_to 'Sign up', signup_path , class: "intro"%></li>
<% end %>
</ul>
</div><!-- /.navbar-collapse -->
</div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>FirstProject</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<%= render "layouts/navigation" %>
<ul>
<% flash.each do|name, msg| 	%>
	<li><%= msg %></li>	
<% end %>
</ul>

<div class="container">
<%= yield %>
</div>

<%= render "layouts/footer" %>
<%= debug(params) if Rails.env.development? %>
</body>
</html>

app/views/users/_form.html.erb
<div class='row'>
<div class='col-xs-12'>
<%= form_for(@user, :html => {class: "form-horizontal", role: "form"}) do |f| %>
<div class="form-group">
<div class="control-label col-sm-2">
<%= f.label :username %>
</div>
<div class="col-sm-8">
<%= f.text_field :username, class: "form-control", placeholder: "Enter username", autofocus: true %>
</div>
</div>
<div class="form-group">
<div class="control-label col-sm-2">
<%= f.label :email %>
</div>
<div class="col-sm-8">
<%= f.email_field :email, class: "form-control", placeholder: "Enter email" %>
</div>
</div>
<div class="form-group">
<div class="control-label col-sm-2">
<%= f.label :password %>
</div>
<div class="col-sm-8">
<%= f.password_field :password, class: "form-control", placeholder: "Enter password" %>
</div>
</div>
<div class="form-group">
<div class="col-sm-offset-2 col-sm-10">
<%= f.submit(@user.new_record? ? "Sign up" : "Update account", class: 'btn btn-primary btn-lg') %>
</div>
</div>
<% end %>
<div class="col-xs-4 col-xs-offset-4">
[ <%= link_to "Cancel request and return to articles listing", articles_path %> ]
</div>
</div>
</div>

app/views/users/edit.html.erb
<h1> Update user</h1>
<%= render "form" %>

app/views/users/index.html.erb
<h1 align="center">All Alpha Bloggers</h1>
<div align="center">
<% @users.each do |user| %>
<ul class="listing">
<div class="row">
<div class="well col-md-4 col-md-offset-4">
<li><%= link_to gravatar_for(user), user_path(user) %></li>
<li class="article-title">
<%= link_to user.username, user_path(user) %>
</li>
<li><small><%= pluralize(user.articles.count, "article") if user.articles %></small></li>
<% if logged_in? and current_user.admin? %>
<li><%= link_to "Delete this user", user_path(user), method: :delete,
data: { confirm: "Are you sure you want to delete the user and all their articles?" } %></li>
<% end %>
</div>
</div>
</ul>
<% end %>
</div>
<div align="center">
<%= will_paginate %>
</div>

app/views/users/new.html.erb
<h1 align="center">Signup for Alpha Blog</h1>
<%= render "form" %>

app/views/users/show.html.erb
<h1 align="center">Welcome to <%= @user.username %>'s page</h1>
<div class="row">
<div class="col-md-4 col-md-offset-4 center">
<%= gravatar_for @user, size: 150 %>
</div>
</div>
<h4 align="center"><%= @user.username %>'s articles</h4>
<%= render 'articles/article', obj: @user.articles %>
<div class="center">
<%= will_paginate @user_articles %>
</div>